#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
$dotenv->load();

if ($argv[1] === 'serve') {
  define('PORT', $_ENV['PORT'] || 8001);
  shell_exec("php -S localhost:{$_ENV['PORT']} public/index.php");
}
